### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by maxbirnbacher** [CTF-Citadel/webapp#15]
As an admin, I want to manage users (ban/delete, suspending, reset password), create challenges, manage events, editing scored points of users.
- [ ] manage users (ban/delete, suspending, reset password)
- [ ] create challenges
- [ ] manage events
- [ ] editing scored points of users

**Comment by 0xk1f0** [comment]
Linking [93b48b3](https://github.com/CTF-Citadel/webapp/commit/93b48b35f0f99df10c4c116bc6950de2e89e1d45)
